/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Emp service. Represents a row in the &quot;EMPLOYEE_Emp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.model.impl.EmpModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.model.impl.EmpImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Emp
 * @generated
 */
@ProviderType
public interface EmpModel extends BaseModel<Emp> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp model instance should use the {@link Emp} interface instead.
	 */

	/**
	 * Returns the primary key of this emp.
	 *
	 * @return the primary key of this emp
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this emp.
	 *
	 * @param primaryKey the primary key of this emp
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this emp.
	 *
	 * @return the uuid of this emp
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this emp.
	 *
	 * @param uuid the uuid of this emp
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the employee ID of this emp.
	 *
	 * @return the employee ID of this emp
	 */
	@AutoEscape
	public String getEmployeeId();

	/**
	 * Sets the employee ID of this emp.
	 *
	 * @param employeeId the employee ID of this emp
	 */
	public void setEmployeeId(String employeeId);

	/**
	 * Returns the name of this emp.
	 *
	 * @return the name of this emp
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this emp.
	 *
	 * @param name the name of this emp
	 */
	public void setName(String name);

	/**
	 * Returns the description of this emp.
	 *
	 * @return the description of this emp
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this emp.
	 *
	 * @param description the description of this emp
	 */
	public void setDescription(String description);

	/**
	 * Returns the mapping ID of this emp.
	 *
	 * @return the mapping ID of this emp
	 */
	@AutoEscape
	public String getMappingId();

	/**
	 * Sets the mapping ID of this emp.
	 *
	 * @param mappingId the mapping ID of this emp
	 */
	public void setMappingId(String mappingId);

}